### ISSUE TITLE
Actualizar la ultima version de adminLTE

### ISSUE THREAD

**Issue by alancornejo** [alancornejo/reportes_calls#1]
Problemas en la visualizacion de la plantilla de adminLTE, la cual ha perdido sus estilos, el problema se genero **desde que se comenzo a usar GULP** (en la version actual del proyecto)

**Comment by jasvir2410** [comment]
Descargar versión 5.1 de laravel

_Sent from my Htc HTC Desire 10 lifestyle using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jasvir2410** [comment]
Instalar laravel 5.1
